In [5]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [6]:
!tar -xvzf "/content/drive/My Drive/yelp_review_polarity_csv.tgz"

yelp_review_polarity_csv/
yelp_review_polarity_csv/train.csv
yelp_review_polarity_csv/readme.txt
yelp_review_polarity_csv/test.csv


In [7]:
!wget "http://nlp.stanford.edu/data/glove.6B.zip"

--2020-05-25 13:59:14--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-05-25 13:59:15--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-05-25 13:59:15--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [8]:
!unzip "glove.6B.zip"

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [0]:
  
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
# print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [10]:
import pandas as pd,numpy as np,seaborn as sns
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
import matplotlib.pyplot as plt
%matplotlib inline
import spacy

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Using TensorFlow backend.


In [0]:
yelp_reviews = pd.read_csv('/content/yelp_review_polarity_csv/train.csv', nrows = 10000)

In [0]:
yelp_reviews.columns = ['label','review']

In [0]:
df = yelp_reviews

In [14]:
df.label[df.label == 1] = 0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [15]:
df.label[df.label == 2] = 1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [16]:
df.head()

label                                             review
0      1  Been going to Dr. Goldberg for over 10 years. ...
1      0  I don't know what Dr. Goldberg was like before...
2      0  I'm writing this review to give you a heads up...
3      1  All the food is great here. But the best thing...
4      0  Wing sauce is like water. Pretty much a lot of...

In [17]:
yelp_reviews.head()

label                                             review
0      1  Been going to Dr. Goldberg for over 10 years. ...
1      0  I don't know what Dr. Goldberg was like before...
2      0  I'm writing this review to give you a heads up...
3      1  All the food is great here. But the best thing...
4      0  Wing sauce is like water. Pretty much a lot of...

In [0]:
nlp = spacy.load('en')

In [0]:
max_num_words = 1000
max_seq_length = 100
tokenizer = Tokenizer(num_words=max_num_words)

In [0]:
texts = df["review"].values
labels = df["label"].values

In [0]:
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
word_index = tokenizer.word_index


In [22]:
len(word_index)

30299

In [23]:
data = pad_sequences(sequences, maxlen=max_seq_length)
data

array([[  0,   0,   0, ...,   2,  66, 632],
       [ 16, 433,  10, ...,  55,   1, 273],
       [  2, 199,  74, ..., 183,  14, 986],
       ...,
       [410, 612,  19, ...,   1,  71,  16],
       [  0,   0,   0, ...,   9,   1, 168],
       [  0,   0,   0, ...,   1, 237,  45]], dtype=int32)

In [24]:
data.shape

(10000, 100)

In [0]:
labels = to_categorical(np.asarray(labels))

In [26]:
labels.shape

(10000, 2)

In [0]:
validation_spilit = 0.2
indices = np.arange(data.shape[0])
np.random.shuffle(indices)

In [28]:
data = data[indices]
data

array([[178,   9,  41, ..., 400, 156,   8],
       [  0,   0,   0, ...,  57,  41, 124],
       [351,   3,   6, ...,  50,   5, 440],
       ...,
       [  0,   0,   0, ...,   9, 665, 165],
       [  0,   0,   0, ...,   0,   0, 832],
       [  1, 980,  63, ...,  71,  57,   5]], dtype=int32)

In [29]:
labels = labels[indices]
labels

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [30]:
nb_validation_samples = int(validation_spilit*data.shape[0])
nb_validation_samples

2000

In [0]:
x_train = data[:-nb_validation_samples]
y_train = labels[:-nb_validation_samples]
x_val = data[-nb_validation_samples:]
y_val = labels[-nb_validation_samples:]


In [0]:
glove_dir = '/content/'

In [33]:
embedding_index = {}

f = open(os.path.join(glove_dir,'glove.6B.100d.txt'))
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:],dtype='float32')
    embedding_index[word] = coefs
f.close()

print('found word vecs: ',len(embedding_index))

found word vecs:  400000


In [34]:
embedding_dim = 100
embedding_matrix = np.zeros((len(word_index)+1,embedding_dim))
embedding_matrix.shape

(30300, 100)

In [0]:
for word,i in word_index.items():
    embedding_vector = embedding_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [0]:
from keras.layers import Embedding
embedding_layer = Embedding(len(word_index)+1,embedding_dim,weights=[embedding_matrix],input_length=max_seq_length,trainable=False)

In [0]:
from keras.layers import Bidirectional,GlobalMaxPool1D,Conv1D
from keras.layers import LSTM,Input,Dense,Dropout,Activation
from keras.models import Model

In [0]:
inp = Input(shape=(max_seq_length,))
x = embedding_layer(inp)
x = Bidirectional(LSTM(100,return_sequences=True,dropout=0.1,recurrent_dropout=0.1))(x)
x = GlobalMaxPool1D()(x)
x = Dense(100,activation='relu')(x)
x = Dropout(0.1)(x)
x = Dense(2,activation='sigmoid')(x)
model = Model(inputs=inp,outputs=x)

In [0]:

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [57]:

print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(y_val.shape)

(8000, 100)
(8000, 2)
(2000, 100)
(2000, 2)


In [58]:
model.fit(x_train,y_train,validation_data=(x_val,y_val),epochs=35,batch_size=128);

Train on 8000 samples, validate on 2000 samples
Epoch 1/35
8000/8000 [==============================] - 35s 4ms/step - loss: 0.6197 - accuracy: 0.6543 - val_loss: 0.4829 - val_accuracy: 0.7815
Epoch 2/35
8000/8000 [==============================] - 34s 4ms/step - loss: 0.4880 - accuracy: 0.7661 - val_loss: 0.3885 - val_accuracy: 0.8360
Epoch 3/35
8000/8000 [==============================] - 34s 4ms/step - loss: 0.4172 - accuracy: 0.8090 - val_loss: 0.3624 - val_accuracy: 0.8405
Epoch 4/35
8000/8000 [==============================] - 35s 4ms/step - loss: 0.3796 - accuracy: 0.8252 - val_loss: 0.3513 - val_accuracy: 0.8555
Epoch 5/35
8000/8000 [==============================] - 35s 4ms/step - loss: 0.3506 - accuracy: 0.8445 - val_loss: 0.3150 - val_accuracy: 0.8675
Epoch 6/35
8000/8000 [==============================] - 35s 4ms/step - loss: 0.3222 - accuracy: 0.8601 - val_loss: 0.2984 - val_accuracy: 0.8785
Epoch 7/35
8000/8000 [==============================] - 35s 4ms/step - loss: 0.313

In [63]:
score = model.evaluate(x_val, y_val)
score


2000/2000 [==============================] - 2s 1ms/step


[0.510255739569664, 0.8767499923706055]

In [62]:
score[1]  *100

87.67499923706055

In [65]:
data1=pd.DataFrame(data)
Label=df['label']


0       1
1       0
2       0
3       1
4       0
       ..
9995    1
9996    0
9997    0
9998    0
9999    0
Name: label, Length: 10000, dtype: int64

In [0]:

from sklearn import metrics
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data1,Label, test_size=0.2)

In [0]:
from sklearn.ensemble import AdaBoostClassifier

# Import Support Vector Classifier
from sklearn.svm import SVC
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
svc=SVC(probability=True, kernel='rbf')

# Create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=svc,learning_rate=1)

# Train Adaboost Classifer
model = abc.fit(X_train, Y_train)

#Predict the response for test dataset
Y_pred = model.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))